apiVersion: apps/v1

kind: Deployment

metadata:
  name: node-app-deployment
spec:

  selector:
    matchLabels:
      app: node
  replicas: 3
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: nodeserver
          image: smia/node_app_light

          ports:
            - containerPort: 3000



          imagePullPolicy: Always