apiVersion: v1

kind: Service

metadata:
  name: node-app-service
  namespace: default
spec:
  ports:
  - nodePort: 30443   # port range 
    port: 100
    protocol: TCP
    targetPort: 3000 
  selector:
     app: node
  type: NodePort 