# k8 is a yml file
# we are going to create a deployment for our nginx-image
# we will create

apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx
spec:

  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: smia/eng110_nginx

          ports:
            - containerPort: 80



          imagePullPolicy: Always